# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2017)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
            ],
            options={
                'db_table': 'period',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ITOM', 'ITOM'), ('IMONSITE', 'IMONSITE')], max_length=10, unique=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('itom', 'ITOM'), ('imlink', 'IMONSITE')], max_length=10)),
                ('class_code', models.CharField(choices=[('msp', 'Service Providers'), ('tenants', 'Tenants'), ('users', 'Users')], max_length=10)),
                ('class_state', models.IntegerField(choices=[(1, 'Active'), (0, 'De-active')])),
                ('month', models.IntegerField(choices=[(0, ''), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField(default=2017)),
                ('count', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'product_statistics',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('msp', 'Service Providers'), ('tenants', 'Tenants'), ('users', 'Users'), ('resources', 'Resources')], max_length=10, unique=True)),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField()),
                ('inactive', models.IntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Period')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Source')),
            ],
            options={
                'db_table': 'product_stats',
            },
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set([('year', 'month')]),
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together=set([('period', 'product', 'source')]),
        ),
    ]
