# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('itom', 'ITOM'), ('imlink', 'IMONSITE')], max_length=10)),
                ('class_code', models.CharField(choices=[('msp', 'Service Providers'), ('clients', 'Clients'), ('users', 'Users')], max_length=10)),
                ('class_state', models.IntegerField(choices=[(1, 'Activated'), (0, 'De-activated')])),
                ('month', models.IntegerField(choices=[(0, ''), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField(default=2017)),
                ('count', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'product_statistics',
            },
        ),
    ]
