# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2017)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
            ],
            options={
                'db_table': 'period',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('ITOM', 'ITOM'), ('IMONSITE', 'IMONSITE')], max_length=10)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('msp', 'Service Providers'), ('tenants', 'Tenants'), ('users', 'Users'), ('resources', 'Resources')], max_length=10)),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField()),
                ('inactive', models.IntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Period')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Products')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Sources')),
            ],
            options={
                'db_table': 'product_stats',
            },
        ),
        migrations.AlterField(
            model_name='productstats',
            name='class_code',
            field=models.CharField(choices=[('msp', 'Service Providers'), ('tenants', 'Tenants'), ('users', 'Users')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productstats',
            name='class_state',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'De-active')]),
        ),
        migrations.AddField(
            model_name='products',
            name='sources',
            field=models.ManyToManyField(through='dashboards.Stats', to='dashboards.Sources'),
        ),
    ]
