# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_auto_20171129_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sources',
        ),
    ]
