# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_remove_products_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sources',
            field=models.ManyToManyField(through='dashboards.Stats', to='dashboards.Sources'),
        ),
    ]
