# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_products_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product',
            field=models.CharField(choices=[('ITOM', 'ITOM'), ('IMONSITE', 'IMONSITE')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sources',
            name='source',
            field=models.CharField(choices=[('msp', 'Service Providers'), ('tenants', 'Tenants'), ('users', 'Users'), ('resources', 'Resources')], max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set([('year', 'month')]),
        ),
    ]
