# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_auto_20171129_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sources',
            old_name='source',
            new_name='name',
        ),
    ]
