# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_auto_20171129_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='sources',
            new_name='source',
        ),
    ]
